### ISSUE TITLE
Is it possible to use GarageMQ as an embedded RabbitMQ/AMQP server?

### ISSUE THREAD

**Issue by aleybovich** [valinurovam/garagemq#80]
I am building an API service for use by a vendor. The API service has various dependencies, like other services it calls or RabbitMQ queues it listens to. I need to build a simulation for teh vendor to use for their testing, that doesn't depend on any external services. For external http services I use httptest, and for external RabbitMQ dependency I am looking for a library that could simulate a running RabbitMQ/AMQP server, but while being a part of my API (the pia will internal talk to the embedded RabbitMQ as if it was real RabbitMQ hosted outside). 

It short, can I somehow run your implementation as a library, starting the AMQP server it from my code?

**Comment by valinurovam** [comment]
Yes, you can use it like a embedded server, like it uses in tests https://github.com/valinurovam/garagemq/blob/master/server/server_basic_test.go#L160

Just confgure, run and use public api where needed.

**Comment by aleybovich** [comment]
Actually, I created a separate issue https://github.com/valinurovam/garagemq/issues/82 for the library update, and submitted a PR for the fix. Closing this issue as resolved
