### ISSUE TITLE
[QUESTION] - Any Golang example for Consumer and Publisher?

### ISSUE THREAD

**Issue by sujit-baniya** [valinurovam/garagemq#95]
Any Golang example for Consumer and Publisher?

**Comment by valinurovam** [comment]
Hey. GarageMQ is a server, like a RabbitMQ. And any examples will suit, for example 
https://github.com/streadway/amqp/tree/master/_examples

If you wanna examples like: we start server, then we start publisher and then test consumer - I can make it.
