### ISSUE TITLE
[POSSIBLE BUG] - Server or badger seems to freeze when consumer is rerun when using Topic Exchange

### ISSUE THREAD

**Issue by sujit-baniya** [valinurovam/garagemq#97]
When using `topic` exchange, the server freezes and doesn't respond.

Code example: https://gist.github.com/sujit-baniya/81894e8b0dc3b1c1f4934b0051e88414

Steps to reproduce:

- Run server
- Run consumer as `go run receive.go "kern.*"`
- Emit payload as `go run emit.go "kern.critical" "A critical kernel error"`
- Close the consumer using `Ctrl + c`
- Rerun the consumer as `go run receive.go "kern.*"`. Here it just freezes

**Comment by valinurovam** [comment]
Yes, I't is really an issue with deadlock when server **delete** queue.
If you create **exclusive** queue server tries to **delete** it when connection closed.

I will try to fix it soon.

**Comment by valinurovam** [comment]
Fix https://github.com/valinurovam/garagemq/pull/99

**Comment by valinurovam** [comment]
Fixed, thank you for report!
